### ISSUE TITLE
Rename repo to more specific title

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/api_documentation#1]
Hi - since this repository was moved into the broad UMNLibraries organization Friday, would you mind renaming it to something more specific? We typically try to prefix the repo name with the project or event it is relevant to. Github preserves old names through redirection so any links in the wild or existing repo clones continue working, though you can also go into your repo clone and update `.git/config` if you wish.

**Comment by liu00222** [comment]
No problem. I need to discuss the new name with Cody and we would rename it by next week.

**Comment by chennesy** [comment]
Hi Michael - thanks for the heads up. Right now the repo includes documentation and code examples to help folks working with the UMedia API, but in the long run we're hoping to add similar docs for UDC/DRUM and potentially MN Reflections and Umbra as well. Specific ipynb notebooks from the repo will be linked from [digital library apis page](https://www.lib.umn.edu/digital/apis). This is all to say: we're open to suggestions for better specific titles! Maybe digital_collection_apis? Not sure what will make most sense on your side of the house. I'll update the repo description for the moment to add some context.

**Comment by mberkowski** [comment]
`digital_collection_apis` sounds fine to me - If these are to be exclusively IPython notebooks in this repo, where other docs might eventually popup for other client sources, you might consider tacking that on like `digital_collection_apis_ipython`. That would leave room for some future hypothetical like `digital_collection_apis_ruby` but if it isn't likely something like that would materialize, don't worry about it. -thanks
